# Generated by Django 4.2 on 2023-04-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="url_path",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
