# Generated by Django 4.2 on 2023-04-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_menuitem_slug_menuitem_url_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ["menu_id", "left"]},
        ),
        migrations.AddField(
            model_name="menuitem",
            name="menu_id",
            field=models.SlugField(blank=True, null=True, verbose_name="Имя меню"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="data",
            field=models.CharField(max_length=100, verbose_name="Название пункта"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menu.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url_path",
            field=models.CharField(max_length=200, verbose_name="URL"),
        ),
    ]
